# Generated by Django 5.2.5 on 2025-11-03 17:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(db_index=True, max_length=50, unique=True)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('account_type', models.CharField(choices=[('guest', 'Invitado'), ('registered', 'Registrado'), ('google', 'Google OAuth')], default='registered', max_length=20)),
                ('is_guest', models.BooleanField(default=False)),
                ('google_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('avatar_url', models.URLField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_emoji', models.CharField(default='🏆', max_length=10)),
                ('requirement_type', models.CharField(choices=[('questions_asked', 'Preguntas Realizadas'), ('animals_explored', 'Animales Explorados'), ('images_generated', 'Imágenes Generadas'), ('streak_days', 'Días Consecutivos'), ('total_points', 'Puntos Totales'), ('sessions_completed', 'Sesiones Completadas')], max_length=50)),
                ('requirement_value', models.IntegerField()),
                ('points_reward', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Logro',
                'verbose_name_plural': 'Logros',
                'db_table': 'achievements',
                'ordering': ['requirement_value'],
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='settings', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('voice_enabled', models.BooleanField(default=False)),
                ('theme', models.CharField(default='default', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Usuario',
                'verbose_name_plural': 'Configuraciones de Usuarios',
                'db_table': 'user_settings',
            },
        ),
        migrations.CreateModel(
            name='AnimalExplored',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('animal_name', models.CharField(max_length=100)),
                ('times_explored', models.IntegerField(default=1)),
                ('is_favorite', models.BooleanField(default=False)),
                ('first_explored_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_explored_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals_explored', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Animal Explorado',
                'verbose_name_plural': 'Animales Explorados',
                'db_table': 'animals_explored',
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Nueva conversación', max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat',
                'verbose_name_plural': 'Chats',
                'db_table': 'chats',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'Usuario'), ('assistant', 'Asistente')], max_length=20)),
                ('message_type', models.CharField(choices=[('text', 'Texto'), ('image', 'Imagen')], default='text', max_length=20)),
                ('text', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('image_alt', models.CharField(blank=True, max_length=500, null=True)),
                ('animal_mentioned', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.chat')),
            ],
            options={
                'verbose_name': 'Mensaje de Chat',
                'verbose_name_plural': 'Mensajes de Chat',
                'db_table': 'chat_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt', models.TextField()),
                ('image_url', models.URLField(max_length=1000)),
                ('animal_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Imagen Generada',
                'verbose_name_plural': 'Imágenes Generadas',
                'db_table': 'generated_images',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GuestSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_token', models.CharField(db_index=True, max_length=255, unique=True)),
                ('user_nickname', models.CharField(blank=True, max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('last_activity_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Sesión de Invitado',
                'verbose_name_plural': 'Sesiones de Invitados',
                'db_table': 'guest_sessions',
                'indexes': [models.Index(fields=['session_token'], name='guest_sessi_session_f3d8fb_idx'), models.Index(fields=['expires_at'], name='guest_sessi_expires_99db9f_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_progress', models.IntegerField(default=0)),
                ('required_progress', models.IntegerField()),
                ('is_unlocked', models.BooleanField(default=False)),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Logro de Usuario',
                'verbose_name_plural': 'Logros de Usuarios',
                'db_table': 'user_achievements',
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_animals_explored', models.IntegerField(default=0)),
                ('total_questions_asked', models.IntegerField(default=0)),
                ('total_images_generated', models.IntegerField(default=0)),
                ('total_sessions', models.IntegerField(default=0)),
                ('current_streak_days', models.IntegerField(default=0)),
                ('longest_streak_days', models.IntegerField(default=0)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('total_points', models.IntegerField(default=0)),
                ('current_level', models.IntegerField(default=1)),
                ('points_to_next_level', models.IntegerField(default=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progreso de Usuario',
                'verbose_name_plural': 'Progreso de Usuarios',
                'db_table': 'user_progress',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='users_usernam_baeb4b_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_guest'], name='users_is_gues_12f373_idx'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('email__isnull', True), ('is_guest', True)), models.Q(('email__isnull', False), ('is_guest', False)), _connector='OR'), name='guest_email_constraint'),
        ),
        migrations.AddIndex(
            model_name='animalexplored',
            index=models.Index(fields=['user', '-last_explored_at'], name='animals_exp_user_id_bfce70_idx'),
        ),
        migrations.AddIndex(
            model_name='animalexplored',
            index=models.Index(fields=['user', 'is_favorite'], name='animals_exp_user_id_5354fc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='animalexplored',
            unique_together={('user', 'animal_name')},
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['user', '-updated_at'], name='chats_user_id_5516a9_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['chat', 'created_at'], name='chat_messag_chat_id_012ed9_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedimage',
            index=models.Index(fields=['user', '-created_at'], name='generated_i_user_id_b538cd_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedimage',
            index=models.Index(fields=['user', 'is_favorite'], name='generated_i_user_id_9220a0_idx'),
        ),
        migrations.AddIndex(
            model_name='userachievement',
            index=models.Index(fields=['user', 'is_unlocked'], name='user_achiev_user_id_eb0544_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userachievement',
            unique_together={('user', 'achievement')},
        ),
    ]
