# Generated by Django 5.2.5 on 2025-11-03 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
